### ISSUE TITLE
Add full CRUD support

### ISSUE THREAD

**Issue by duketon** [evojam/play-elastic4s#17]
We should wrap all CRUD operations on Elastic with Play JSON support.

**Comment by abankowski** [comment]
Summary of requirements:
- [x] support for search
- [x] support for remove
- [x] support for index
- [ ] support for get
- [x] support for bulk index
- [ ] support for bulk get
- [ ] support for bulk remove
- [ ] support for bulk update

**Comment by duketon** [comment]
`get` and `bulk get` added in #22
